### ISSUE TITLE
Cannot get refresh token

### ISSUE THREAD

**Issue by jackcohen5** [jaredhanson/passport-windowslive#11]
I would like to obtain a refresh token so that when my access token expires I can use the passport-oauth-refresh module to obtain a new one, however, refreshToken keeps returning undefined.

I have tried adding the accessType and approvalPrompt parameters like so to no succes:

```
	app.route('/auth/windowslive').get(passport.authenticate('windowslive', {
		scope: [
			'wl.signin',
			'wl.basic',
			'wl.emails',
			'wl.contacts_emails'
		],
		accessType: 'offline',
		approvalPrompt: 'force'
	}));
```

**Comment by jaredhanson** [comment]
Answered in the FAQ: https://github.com/jaredhanson/passport-windowslive#how-do-i-obtain-a-refresh-token
