### ISSUE TITLE
Issue with express (code params)

### ISSUE THREAD

**Issue by Nicolas-ilhe** [jaredhanson/passport-windowslive#12]
Hi, to authenticate, I use passportJS with "passport-windowslive". When I go to my URL, I am redirected to the MS website. I can connect, accept "informations", but I am redirected to the URL (defined in my callback MS) : http://localhost:3003/auth/windowslive/authorize?code=XXX

But on my express route, I got a GET /auth/windowslive/authorize?code=XXX 404 How can handle this "code" parameter in my authentication process?

Thank you, Nicolas

**Comment by jaredhanson** [comment]
If you can, please provide an explanation for what you did to solve this issue.  It will help other people who arrive at this issue via searching for solutions to the problem.
